### ISSUE TITLE
Add support for "nullable": true

### ISSUE THREAD

**Issue by slemrmartin** [ManageIQ/topological_inventory-ingress_api#71]
OpenAPI schema defines "nullable" attribute, which says if property can be set to NULL or not.
OpenAPI Generator doesn't support it for Ruby clients.

--- 

**Issue**: https://github.com/OpenAPITools/openapi-generator/issues/4363
- [x] **Fix**: https://github.com/OpenAPITools/openapi-generator/pull/4391 (Release: November 15 as version 4.2.1)

- Influenced components:
  - Topological Inventory API (+client)
    - [x] https://github.com/ManageIQ/topological_inventory-api/pull/263
    - [x] https://github.com/ManageIQ/topological_inventory-api-client-ruby/pull/24
  - Sources API (+client)
    - [x] https://github.com/ManageIQ/sources-api/pull/122
    - [x] https://github.com/ManageIQ/sources-api-client-ruby/pull/14
  - Ingress API (+client)
    - [x] https://github.com/ManageIQ/topological_inventory-ingress_api/pull/72
    - [x] https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/pull/59

**Comment by slemrmartin** [comment]
@agrare please merge them

**Comment by agrare** [comment]
All PRs merged
